// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: grep.proto

package grep

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GrepService_Search_FullMethodName = "/grep.GrepService/Search"
)

// GrepServiceClient is the client API for GrepService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GrepServiceClient interface {
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SearchResponse], error)
}

type grepServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGrepServiceClient(cc grpc.ClientConnInterface) GrepServiceClient {
	return &grepServiceClient{cc}
}

func (c *grepServiceClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SearchResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GrepService_ServiceDesc.Streams[0], GrepService_Search_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SearchRequest, SearchResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GrepService_SearchClient = grpc.ServerStreamingClient[SearchResponse]

// GrepServiceServer is the server API for GrepService service.
// All implementations must embed UnimplementedGrepServiceServer
// for forward compatibility.
type GrepServiceServer interface {
	Search(*SearchRequest, grpc.ServerStreamingServer[SearchResponse]) error
	mustEmbedUnimplementedGrepServiceServer()
}

// UnimplementedGrepServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGrepServiceServer struct{}

func (UnimplementedGrepServiceServer) Search(*SearchRequest, grpc.ServerStreamingServer[SearchResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedGrepServiceServer) mustEmbedUnimplementedGrepServiceServer() {}
func (UnimplementedGrepServiceServer) testEmbeddedByValue()                     {}

// UnsafeGrepServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GrepServiceServer will
// result in compilation errors.
type UnsafeGrepServiceServer interface {
	mustEmbedUnimplementedGrepServiceServer()
}

func RegisterGrepServiceServer(s grpc.ServiceRegistrar, srv GrepServiceServer) {
	// If the following call pancis, it indicates UnimplementedGrepServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GrepService_ServiceDesc, srv)
}

func _GrepService_Search_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SearchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GrepServiceServer).Search(m, &grpc.GenericServerStream[SearchRequest, SearchResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GrepService_SearchServer = grpc.ServerStreamingServer[SearchResponse]

// GrepService_ServiceDesc is the grpc.ServiceDesc for GrepService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GrepService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grep.GrepService",
	HandlerType: (*GrepServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Search",
			Handler:       _GrepService_Search_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "grep.proto",
}
